version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: "@storybook/addon-actions"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addon-links"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addons"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/vue"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: vue-context
    versions:
    - ">= 4.a, < 5"
  - dependency-name: vue-context
    versions:
    - ">= 5.a, < 6"
  - dependency-name: vue-context
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.13
    - 7.13.14
    - 7.13.16
    - 7.13.8
  - dependency-name: rollup
    versions:
    - 2.41.0
    - 2.45.2
  - dependency-name: cross-fetch
    versions:
    - 3.1.0
    - 3.1.4
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.1
    - 5.1.2
  - dependency-name: vue-style-loader
    versions:
    - 4.1.3
  - dependency-name: typescript
    versions:
    - 4.1.5
